# Generated by Django 4.2.1 on 2023-05-24 11:40

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='آیتم محصول')),
            ],
            options={
                'verbose_name': 'آیتم اضافی',
                'verbose_name_plural': 'آیتم های اضافی',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='اسلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد دسته بندی')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category', verbose_name='زیردسته')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی\u200c ها',
                'ordering': ['parent__id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='کد محصول')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='کد محصول')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت(ریال)')),
                ('post_price', models.PositiveIntegerField(default=50, verbose_name='هزینه ارسال')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='درصد تخفیف')),
                ('battery_capacity', models.CharField(blank=True, max_length=55, null=True, verbose_name='ظرفیت باتری')),
                ('maximum_torque', models.CharField(blank=True, max_length=55, null=True, verbose_name='حداکثر گشتاور')),
                ('speed_range', models.CharField(blank=True, max_length=55, null=True, verbose_name='بازه سرعتی')),
                ('speed_gear', models.CharField(blank=True, max_length=55, null=True, verbose_name='تعداد دنده های سرعت')),
                ('weight', models.CharField(max_length=55, verbose_name='وزن')),
                ('dimensions', models.CharField(blank=True, max_length=55, null=True, verbose_name='ابعاد')),
                ('hammer_mode', models.BooleanField(default=False, verbose_name='حالت چکشی')),
                ('hit_per_minute', models.IntegerField(blank=True, null=True, verbose_name='ضربه در دقیقه')),
                ('chuck_capacity', models.IntegerField(blank=True, null=True, verbose_name='ظرفیت سه نظام')),
                ('has_battery', models.BooleanField(default=False, verbose_name='باتری دارد')),
                ('spare_battery', models.BooleanField(default=False, verbose_name='باتری یدک')),
                ('left_right_movement', models.BooleanField(default=False, verbose_name='گردش چپ راست')),
                ('has_box', models.BooleanField(default=False, verbose_name='جعبه دارد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='کشور سازنده')),
                ('additional_items', models.ManyToManyField(blank=True, null=True, related_name='items', to='product.additionalitems', verbose_name='آیتم اضافی')),
                ('category', models.ManyToManyField(related_name='videos', to='product.category', verbose_name='دسته بندی')),
                ('image', models.ManyToManyField(related_name='images', to='product.image', verbose_name='تصاویر محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ('-created_at',),
            },
        ),
    ]
