# Generated by Django 4.2.1 on 2023-06-29 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان دسته بندی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/img/', verbose_name='تصویر دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='اسلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد دسته بندی')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category', verbose_name='زیردسته')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی\u200c ها',
                'ordering': ['parent__id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='کد محصول')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان محصول')),
                ('country', models.CharField(max_length=50, verbose_name='کشور مونتاژ کننده')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='درصد تخفیف')),
                ('discounted_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت تخفیف خورده (تومان)')),
                ('weight', models.CharField(max_length=30, verbose_name='وزن')),
                ('total_weight', models.FloatField(blank=True, null=True, verbose_name='وزن همراه جعبه (کیلوگرم)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale_count', models.IntegerField(default=0, verbose_name='تعداد فروش')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product.category', verbose_name='دسته بندی')),
                ('proper_tools', models.ManyToManyField(blank=True, null=True, related_name='proper_tools', to='product.product', verbose_name='ابزارهای مناسب')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان')),
                ('text', models.CharField(max_length=30, verbose_name='توضیح کوتاه')),
                ('image', models.ImageField(upload_to='sliders/images/', verbose_name='عکس اسلایدر (۱۹۲۰ * ۵۰۰)')),
                ('url', models.URLField(null=True, verbose_name='آدرس برای هدایت کاربر')),
                ('button_text', models.CharField(default='اکنون خرید کنید', max_length=20, verbose_name='متن دکمه آدرس')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='مشخصه')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='مقدار مشخصه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصه فنی',
                'verbose_name_plural': 'مشخصات فنی',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='products/img/', verbose_name='تصویر محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='product.product')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصویر محصول',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='product.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'علاقه مندی',
                'verbose_name_plural': 'علاقه مندی ها',
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام کد تخفیف')),
                ('percent', models.PositiveIntegerField(default=0, verbose_name='درصد')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('used_by', models.ManyToManyField(blank=True, null=True, related_name='discounts', to=settings.AUTH_USER_MODEL, verbose_name='استفاده شده توسط')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد های تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productcompare1', to='product.product', verbose_name='کالای اول')),
                ('product2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productcompare2', to='product.product', verbose_name='کالای دوم')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparison', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='متن کامنت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='product.comment', verbose_name='کامنت پدر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product', verbose_name='محصول مربوطه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='AdditionalItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=155, verbose_name='اقلام محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_items', to='product.product')),
            ],
            options={
                'verbose_name': 'اقلام محصول',
                'verbose_name_plural': 'اقلام همراه',
            },
        ),
    ]
