# Generated by Django 4.2.1 on 2023-06-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proper_tools',
            field=models.ManyToManyField(related_name='proper_tools', to='product.product', verbose_name='ابزارهای مناسب'),
        ),
    ]
