# Generated by Django 4.2.1 on 2023-06-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان')),
                ('text', models.CharField(max_length=30, verbose_name='توضیح کوتاه')),
                ('image', models.ImageField(upload_to='sliders/images/', verbose_name='عکس اسلایدر (۱۹۲۰ * ۵۰۰)')),
                ('url', models.URLField(null=True, verbose_name='آدرس برای هدایت کاربر')),
                ('button_text', models.CharField(default='اکنون خرید کنید', max_length=20, verbose_name='متن دکمه آدرس')),
            ],
        ),
    ]
