# Generated by Django 4.2.1 on 2023-06-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(max_length=50, verbose_name='کشور مونتاژ کننده'),
        ),
    ]
