# Generated by Django 4.2.1 on 2023-05-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='box',
        ),
        migrations.RemoveField(
            model_name='product',
            name='power_battery',
        ),
        migrations.AddField(
            model_name='product',
            name='battery_capacity',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='ظرفیت باتری'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_battery',
            field=models.BooleanField(default=False, verbose_name='باتری دارد'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_box',
            field=models.BooleanField(default=False, verbose_name='جعبه دارد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='ابعاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hammer_mode',
            field=models.BooleanField(blank=True, null=True, verbose_name='حالت چکشی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='maximum_torque',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='حداکثر گشتاور'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spare_battery',
            field=models.BooleanField(default=False, verbose_name='باتری یدک'),
        ),
        migrations.AlterField(
            model_name='product',
            name='speed_gear',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='تعداد دنده های سرعت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='speed_range',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='بازه سرعتی'),
        ),
    ]
