# Generated by Django 4.2.1 on 2023-06-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='call_before',
            field=models.BooleanField(default=False, verbose_name='تماس قبل از خرید'),
        ),
    ]
