# Generated by Django 4.2.1 on 2023-06-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='created_at',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
    ]
