# Generated by Django 4.2.1 on 2023-05-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalitems',
            options={'verbose_name': 'اقلام محصول', 'verbose_name_plural': 'اقلام همراه'},
        ),
        migrations.AlterField(
            model_name='additionalitems',
            name='item',
            field=models.CharField(max_length=155, verbose_name='اقلام محصول'),
        ),
    ]
