# Generated by Django 4.2.1 on 2023-06-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='وزن همراه جعبه (کیلوگرم)'),
        ),
    ]
