# Generated by Django 4.2.1 on 2023-05-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_additionalitems_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام کد تخفیف')),
                ('percent', models.PositiveIntegerField(default=0, verbose_name='درصد')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد﴿')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد های تخفیف',
            },
        ),
    ]
