# Generated by Django 4.2.1 on 2023-05-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_box_remove_product_power_battery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chuck_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='ظرفیت سه نظام'),
        ),
        migrations.AddField(
            model_name='product',
            name='hit_per_minute',
            field=models.IntegerField(blank=True, null=True, verbose_name='ضربه در دقیقه'),
        ),
        migrations.AddField(
            model_name='product',
            name='left_right_movement',
            field=models.BooleanField(default=False, verbose_name='گردش چپ راست'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hammer_mode',
            field=models.BooleanField(default=False, verbose_name='حالت چکشی'),
        ),
    ]
