# Generated by Django 4.2.1 on 2023-06-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_proper_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='proper_tools',
            field=models.ManyToManyField(blank=True, null=True, related_name='proper_tools', to='product.product', verbose_name='ابزارهای مناسب'),
        ),
    ]
