# Generated by Django 4.2.1 on 2023-07-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_call_before'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('discount',), 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ قرارگیری در سایت'),
        ),
    ]
