# Generated by Django 4.2.1 on 2023-06-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_weight',
            field=models.IntegerField(default=1, max_length=30, verbose_name='وزن کل'),
            preserve_default=False,
        ),
    ]
