# Generated by Django 4.2.1 on 2023-06-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدرها'},
        ),
    ]
