# Generated by Django 4.2.1 on 2023-06-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_proper_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/img/', verbose_name='تصویر دسته بندی'),
        ),
    ]
