# Generated by Django 4.2.1 on 2023-05-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_chuck_capacity_product_hit_per_minute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
