# Generated by Django 4.2.1 on 2023-05-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_items', to='product.product'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
