# Generated by Django 4.2.1 on 2023-05-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='کد محصول'),
        ),
    ]
