# Generated by Django 4.2.1 on 2023-06-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_discountcode_used_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='used_by',
        ),
    ]
