# Generated by Django 4.2.1 on 2023-06-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_count',
            field=models.IntegerField(default=0, verbose_name='تعداد فروش'),
        ),
    ]
