# Generated by Django 4.2.1 on 2023-06-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_sale_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت تخفیف خورده (تومان)'),
        ),
    ]
