# Generated by Django 4.2.1 on 2023-07-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_proper_tools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='percent',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداقل قیمت'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='product.product', verbose_name='قابل استفاده برای محصولات'),
        ),
    ]
