# Generated by Django 4.2.1 on 2023-07-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_discountcode_percent_discountcode_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='product',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='قابل استفاده برای محصولات'),
        ),
    ]
