# Generated by Django 4.2.1 on 2023-07-08 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0009_remove_comparison_product1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
