# Generated by Django 4.2.1 on 2023-07-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_comparison_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__id', '-id'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی\u200c ها'},
        ),
        migrations.AlterModelOptions(
            name='comparison',
            options={'verbose_name': 'مقایسه', 'verbose_name_plural': 'مقایسه\u200cها'},
        ),
    ]
