# Generated by Django 4.2.1 on 2023-08-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_category_options_alter_comparison_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='درصد تخفیف'),
        ),
    ]
