# Generated by Django 4.2.1 on 2023-07-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='post_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='post_tracking_code',
        ),
    ]
