# Generated by Django 4.2.1 on 2023-06-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='post_tracking_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد رهگیری پست'),
        ),
    ]
