# Generated by Django 4.2.1 on 2023-06-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_post_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری پست'),
        ),
    ]
