# Generated by Django 4.2.1 on 2023-07-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_order_delivery_method_remove_order_is_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_applied',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='کد تخفیف اعمال شده'),
        ),
    ]
