# Generated by Django 4.2.1 on 2023-06-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_orderitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_applied',
            field=models.BooleanField(default=False, verbose_name='تخفیف اعمال شده'),
        ),
    ]
