# Generated by Django 4.2.1 on 2023-06-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_discount_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='post_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت پست'),
        ),
    ]
