# Generated by Django 4.2.1 on 2023-06-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_order_post_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='ارسال شده'),
        ),
    ]
