# Generated by Django 4.2.1 on 2023-05-20 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('fullname', models.CharField(max_length=100, verbose_name='نام و نام خوانوادگی')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='users/profile', verbose_name='عکس پروفایل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('postal_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='کد پستی')),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2023, 5, 20, 17, 11, 22, 401816, tzinfo=datetime.timezone.utc), verbose_name='تاریخ عضویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت کاربر')),
                ('is_admin', models.BooleanField(default=False, verbose_name='مدیر')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=155, null=True, verbose_name='توکن اعتبارسنجی')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='گذرواژه')),
                ('code', models.CharField(max_length=6, verbose_name=' کد فعالسازی')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'کد اعتبارسنجی',
                'verbose_name_plural': 'کدهای اعتبارسنجی',
            },
        ),
    ]
