# Generated by Django 4.2.1 on 2023-05-20 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='fullname',
            field=models.CharField(max_length=50, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 17, 20, 47, 186378, tzinfo=datetime.timezone.utc), verbose_name='تاریخ عضویت'),
        ),
    ]
