# Generated by Django 4.2.1 on 2023-06-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='تلگرام'),
        ),
        migrations.AddField(
            model_name='info',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='توییتر'),
        ),
    ]
