# Generated by Django 4.2.1 on 2023-05-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_avatar_alter_user_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditedUser',
            fields=[
                ('otp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.otp')),
                ('new_phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل جدید')),
            ],
            options={
                'verbose_name': 'کد تایید ویرایش پروفایل',
                'verbose_name_plural': 'کدهای تایید ویرایش پروفایل',
            },
            bases=('accounts.otp',),
        ),
        migrations.AlterField(
            model_name='otp',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام و نام خانوادگی'),
        ),
    ]
