# Generated by Django 4.2.1 on 2023-07-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'بازخورد مقاله', 'verbose_name_plural': 'بازخورد مقالات'},
        ),
    ]
